version: "3.9"
services:




  auth:
    image: "auth-image"
    build:
      context: ./NestJS_MicroServices/apps/auth/
      dockerfile: ./Dockerfile
    container_name: auth-container
    networks:
      - office-network
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev auth --prefix "./NestJS_MicroServices" # overrides CMD from dockerfile

  mysql:
    image: "mysql:8.3"
    networks:
      - office-network
    container_name: mysql-container 
    environment:
      #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_DATABASE=hr_management_platform
      - MYSQL_ROOT_PASSWORD=axelites_pwd
      - MYSQL_SYNCHRONIZE=true
    ports:
      - "3306:3306"
    restart: unless-stopped  
    volumes: # you need to delete this volume or else docker will only create the db the first time
    # then it will look into this volume and does not check if it exist or not (docker volume ls - docker volume rm 5twingraduationproject_db) 
      - db:/var/lib/mysql


volumes:
  db:


networks:
  office-network:
    driver: bridge

