spring:
  cloud:
    gateway:
      discovery:
        locator:
          # lower-case-service-id: true
          enabled: true
      routes:
        - id: AUTH_SERVICE
          uri: ${AUTH_SERVICE_URL:-http://localhost:3000}
          predicates:
            - Path=/auth/**,/permissions/**,/users/**,/roles/**

        - id: order-mission
          uri: ${ORDER_MISSION_SERVICE_URL:-http://localhost:3001}
          predicates:
            - Path=/order-mission/**,/tasks/**,/users/**

        - id: leave-management
          uri: ${leave-management_SERVICE_URL:-http://localhost:3004}
          predicates:
            - Path=/leave/**

        - id: TEST_SERVICE
          uri: ${TEST_SERVICE_URL:-http://localhost:3002}
          predicates:
            - Path=/test/**

        - id: MATERIAL_SERVICE
          uri: ${MATERIAL_SERVICE_URL:-http://localhost:3002}
          predicates:
            - Path=/materials/**,/vehicles/**,/categories/**

      #Cors Configuration:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true

logging:
  level:
    org.springframework.web: DEBUG
