version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    hostname: rabbitmq 
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  mysql2:
    image: "mysql:8.3"
    container_name: mysql-container 
    environment:
      #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
      #- MYSQL_USER=root
      - MYSQL_DATABASE=mytestdatabase
      - MYSQL_ROOT_PASSWORD=axelites_pwd
      - MYSQL_SYNCHRONIZE=true
    ports:
      - "3307:3306"
    restart: unless-stopped  
    volumes: # you need to delete this volume or else docker will only create the db the first time
    # then it will look into this volume and does not check if it exist or not (docker volume ls - docker volume rm 5twingraduationproject_db) 
      - db:/var/lib/mysql

volumes:
  db: